name = "Create New Horizon"
author = "mo_guang"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc3fba4577ca1dd83deef07c33939a0c898eece3d94b4603c35f462665d3821"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
