name = "Create New Horizon"
author = "mo_guang"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84fc7fb07a6676f071928fcc822d059823e15c3a49da619b3df5f838e0c263f"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
