name = "Create New Horizon"
author = "mo_guang"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd387d2aaab4726da8ace331321b26d2b81aca4954dc420a7591789383edb40"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
