name = "Create New Horizon"
author = "mo_guang"
version = "1.3.0.z"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ad31c6524c832fa42c123f5dd8a4e0defcf102c969d697da1e15e6e8253f56f"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
