name = "Create New Horizon"
author = "mo_guang"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4785dccced616db587576f42dfb5ad9667f6a5d2dcd490b06239bebcfc84db10"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
