name = "Create New Horizon"
author = "mo_guang"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3321bc5ecdb53d5b8bbadb50cb1cd04118137519133a781c1650b6cc26e3f59"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
