name = "Create New Horizon"
author = "mo_guang"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c903d1d3b727f3fbb2c1d92bee04e32a5ca00b342ee98443e74493569be8216a"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
