name = "Create New Horizon"
author = "mo_guang"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5ef51c87dc41ecb1eb64d9ac0cb55617fa37dc4796bc9b667d75ba855f7d991"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
