name = "Create New Horizon"
author = "mo_guang"
version = "1.3.4-snapshot"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c73d280fe42c47913ff25a25393bcb543f0e038a914cea7d3cd4a63e8856ecf"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
