name = "Create New Horizon"
author = "mo_guang"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "624b07004fa169872bf8275b4a821e5759420164c6b8a3327e8019ae3e725b7a"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
