name = "Create New Horizon"
author = "mo_guang"
version = "1.3.4-snapshot"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec71ec5eedc9a67a4d4753186c72e5448da536fd48ad03df10ea00eeeb4b604"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
