name = "Create New Horizon"
author = "mo_guang"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8184af4e45126a5fbf7b1fb33c821592a6d1705519002712c9313b64a7a1ad7"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
