name = "Create New Horizon"
author = "mo_guang"
version = "1.3.4-snapshot"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f11b10a0f032d4233067c2c65ae2a86759427e4f735daf5165358944c1c24dcb"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
