name = "Create New Horizon"
author = "mo_guang"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ba4a89341eb61dd725e79bfcdb18e41a4abf3ad6b24faf775f8abacaccfa872"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
